name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Upgrade compiler to GCC 13
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-13 gcc-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev
      - name: Build and run tests
        run: |
          chmod +x ./scripts/run_tests.sh
          ./scripts/run_tests.sh
